version: 2

jobs:
  test-3.6: &test-template
  # Job to run tests test on python 3.6
    docker:
      - image: circleci/python:3.6

    environment:
      PYTHON_BIN: python3
      PYTHON_VERSION: 3.6

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}

      - run:
          name: Install test dependencies
          command: |
            ${PYTHON_BIN} -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -U setuptools
            # Install package with dependencies
            pip install .[test]

      - save_cache:
          paths:
            - ./venv
          key: v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}

      # run Flake8!
      - run:
          name: Flake8 Compliance
          command: |
            . venv/bin/activate
            ${PYTHON_BIN} setup.py flake8

      # run tests!
      - run:
          name: Unit-Tests
          command: |
            . venv/bin/activate
            pip install
            ${PYTHON_BIN} setup.py nosetests

  test-3.5:
  # Clone-job to run tests test on python 3.6
    <<: *test-template
    docker:
      - image: circleci/python:3.5

    environment:
      PYTHON_BIN: python3
      PYTHON_VERSION: 3.5

  build:
    # Build and store artifacts

    docker:
      - image: circleci/python:3.6


    steps:
      - checkout
      - run:
          name: Create environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools wheel

      - run:
          name: Build Source and Wheel distribution files
          command: |
            . venv/bin/activate
            python setup.py sdist bdist_wheel
            python setup.py --version > version.txt

      - store_artifacts:
          path: dist
          destination: dist

      - persist_to_workspace:
          root: .
          paths:
            - dist
            - version.txt

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test-3.6
      - test-3.5
      - build:
          requires:
            - test-3.6
            - test-3.5
