# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
jobs:
  test-3.6: &test-template
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-test-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-test-dependencies-

      - run:
          name: Install test dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -U setuptools
            # Install package with dependencies
            pip install .[test]

      - save_cache:
          paths:
            - ./venv
          key: v1-test-dependencies-{{ checksum "setup.py" }}

      # run Flake8!
      - run:
          name: Flake8 Compliance
          command: |
            . venv/bin/activate
            python setup.py flake8

      # run tests!
      - run:
          name: Unit-Tests
          command: |
            . venv/bin/activate
            pip install
            python setup.py nosetests

#      # Build
#      - store_artifacts:
#          path: test-reports
#          destination: test-reports

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5

  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7
